Revert "nvidia_driver: updated beta version to 190.25"
This reverts commit 3c08d353f1820b4c8f7b01bdf5d1a8a6a8f718d9.

Breaks with Thread Local Storage enabled in xorg-server (and maybe
without, I haven't tried).

Examples:

kdebase4-runtime and compiz:
/usr/lib/libnvidia-tls.so.1: undefined reference to
`__unixTLSWWMPDlsym(void*, char const*)'
collect2: ld returned 1 exit status

wine:
checking for -lGLU... configure: error: No OpenGL library found on this
system.

Simply reverting to 190.18 fixes this.